### ISSUE TITLE
Duplicate device ID

### ISSUE THREAD

**Issue by vera3224** [jhonny-me/install_on_iOS#11]
Connected to 3 devices, list 4 device ID
![image](https://cloud.githubusercontent.com/assets/11629849/24136880/0c046db2-0e4c-11e7-8e41-8fffbfe4ba5c.png)

**Comment by jhonny-me** [comment]
fixed in https://github.com/jhonny-me/install_on_iOS/commit/729db63c2e709a698f5b48da9250658175f210f4

closing.
